# Generated by Django 4.1.5 on 2023-01-21 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videos', models.URLField(verbose_name='Lessons')),
                ('files', models.FileField(upload_to='course_files', verbose_name='Files')),
                ('test', models.URLField(verbose_name='Test')),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('studients', models.IntegerField(verbose_name="Studient's count")),
                ('summry', models.TextField(max_length=1000, verbose_name='Summry')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('rate', models.IntegerField(verbose_name='Rate')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('details', models.TextField(max_length=1000, verbose_name='details')),
                ('image', models.ImageField(upload_to='courses_images', verbose_name='images')),
                ('lang', models.CharField(max_length=50, verbose_name='Language')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_at')),
                ('requerment', models.TextField(max_length=1000, verbose_name='Requerment')),
                ('price', models.IntegerField(verbose_name='price')),
                ('studients', models.IntegerField(verbose_name="Studient's count")),
                ('content', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='coursers.content', verbose_name='Content')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instractor_course', to='coursers.instructor', verbose_name='Instructor')),
            ],
        ),
        migrations.CreateModel(
            name='CourseReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('rate', models.IntegerField(verbose_name='Rate')),
                ('review', models.TextField(max_length=1000, verbose_name='course_review')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_review', to='coursers.courses', verbose_name='Course')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_review', to=settings.AUTH_USER_MODEL, verbose_name='user_review')),
            ],
        ),
    ]
